# GeneralUtils config

back-enabled: true
# Allows usage of /back command.

kickall-exempt-enabled: true
# Disable kickall exemption

messages:
  # Color codes are supported here. placeholderapi implementation is planned, but not added yet

  kickall-message: '&4Kickall command was used!'
  # Kick reason for kickall usage

  staffchat-prefix: '&5[StaffChat] '
  # Prefix for staffchat ([Prefix] sender > message)




# DO NOT CHANGE THIS
config-version: 1