# GeneralUtils config

back-enabled: true
# Allows usage of /back command.

kickall-exempt-enabled: true
# Disable kickall exemption

messages:
  permission-message: 'You don''t have permission to use this!'
  # Message that shows when player has insufficient permissions

  kickall-message: 'Kickall command was used!'
  # Kick reason for kickall usage

  staffchat-prefix: '&5[StaffChat] '
  # Prefix for staffchat ([Prefix] sender > message)




# DO NOT CHANGE THIS
config-version: 1