# GeneralUtils config

back-enabled: true
# Allows usage of /back command.

kickall-exempt-enabled: true
# Disable kickall exemption

messages:
  # Color codes are supported here. PlaceholderAPI will work for all messages if installed.

  kickall-message: '&4Kickall command was used!'
  # Kick reason for kickall usage

  staffchat-prefix: '&5[StaffChat] &l<sender>&r&5 >&f '
  # Prefix for staffchat (<sender> is a placeholder for the senders username.)




# DO NOT CHANGE THIS
config-version: 2