name: GeneralUtils
version: '${version}'
main: me.alecjensen.generalutils.GeneralUtils
api-version: 1.21
authors: [ "Alec Jensen" ]
description: A general utilities plugin made by Alec Jensen
softdepend: [ "PlaceholderAPI" ]
permissions:
  generalutils.reload:
    description: Allow reloading of the config
    default: op
  generalutils.bring:
    description: Allow bringing of players
    default: op
  generalutils.to:
    description: Allow going to players
    default: op
  generalutils.back:
    description: Go to your location pre-teleport
    default: true
  generalutils.kickall:
    description: Allow kickall command usage
    default: op
  generalutils.kickall.exempt:
    description: Don't be kicked when kickall is used (can be disabled in config)
    default: op
  generalutils.staffchat:
    description: Send and recieve staffchat messages
    default: op
  generalutils.announce:
    description: Allow people to send announcements
    default: op
  generalutils.suicide:
    description: Kills you
    default: true
  generalutils.clearchat:
    description: Clear the chat.
    default: op
  generalutils.freeze:
    description: Allow to freeze/unfreeze players
    default: op
  generalutils.freeze.exempt:
    description: Players with this permission cannot be frozen
    default: op
  generalutils.mute:
    description: Allow to mute/unmute players
    default: op
  generalutils.tempban:
    description: Allow to temporarily ban players
    default: op